Feature/tag alertas
MinisterioPublicoRJ/apimpmapas pull request #324
Opened 2021-11-05 17:13 UTC by EBarbara

Já criei o PR, mas ainda tenho que escrever um caso de teste pra quando tem alertas retornando no suamesa. 
Os testes atuais passaram todos.

2021-11-10 22:00 UTC, bernardoccordeiro requested changes

2021-12-03 19:46 UTC, EBarbara commented on dominio/tutela/dao.py
> +
DAOs unidos em um só

2021-12-06 22:09 UTC, EBarbara commented on dominio/tutela/tests/test_suamesa.py
>                  "numero_externo": "tj1234",
Acessos mockados.

2021-12-07 20:43 UTC, bernardoccordeiro approved these changes

2021-12-07 20:48 UTC, merged